### ISSUE TITLE
Implementar a ordem dos documentos recuperados conforme o tipo dos mesmos

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/BVS-InfoButton#11]
"Verônica, e qual seria a ordem de interesse para consumo imediato de um profissional que esteja na clínica médica?"  Renato Murassaki

Resposta da Verônica:

·        [ 6   ] Relato de casos (1900959)
·        [ 5 ] Estudo de casos e controles (235956)
·        [ 4 ] Estudo de coorte (208157)
·        [ 1 ] Guia de prática clínica (38813)
·        [ 3 ] Ensaio clínico controlado (19088)
·        [ 2 ] Revisão sistemática (16400)
·        [   ] Avaliação de tecnologias de saúde(10644)
·        [  ] Overview (10210)
·        [   ] Avaliação econômica em saúde(7544)
·        [  ] Síntese de evidências (2131)
 
Para quem está na clínica médica as avaliações de tecnologia e econômicas, overviews e sínteses não interessam muito, seria mais para quem está na gestão.

**Comment by heitorbarbieri** [comment]
@renatomurasaki , dado que em um resultado de pesquisa nenhum dos seis tipos de publicação apareça, deve-se não apresentar nenhum documento ou apresentar os mais recentes independentemente do tipo?

**Comment by renatomurasaki** [comment]
Em uma primeira versão apresentar o que tem em ordem decrescente de publicação.
Em uma versão futura seria interessante fazer a requisição em 2 etapas, onde a primeira retorna os links para cada tipo de documento, podendo o usuário escolher qual lista acessar.

Renato

**Comment by heitorbarbieri** [comment]
Acrescentei 'overview' no fim da lista apenas para garantir que algum documento seja retornado caso os documentos dos tipos anteriores não sejam em número suficiente.

**Comment by heitorbarbieri** [comment]
A primeira versão foi implementada.
A sugestão para a segunda versão foi migrada para o issue #27
