### ISSUE TITLE
Implementar a possibilidade de busca por código CID-x

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/BVS-InfoButton#2]
Atualmente a busca por código somente permite o uso de código Mesh, deve-se dar também a opção pelo uso de código CID-9 e CID-10.

**Comment by heitorbarbieri** [comment]
@renatomurasaki ,

Precisamos conversar sobre a qualidade dos possíveis documentos recuperados dado um código CID10 entrado.
Quando o usuário entra com o código 'Z90' do CID10, o sistema tenta encontrar um código semelhante no MeSH. Como não encontra, o que resta fazer é uma busca com o texto que define o Z90, que é: "Acquired absence of organs, not elsewhere classified".

1) Procurando no portal por "acquired absence of organs, not elsewhere classified""
    -> nenhum documento encontrado

2) Procurando no portal por "acquired absence of organs"
    -> 183 documentos encontrados
    -> títulos dos 4 primeiros da lista:
           a) Cross-Tissue Transcriptomic Analysis of Human Secondary Lymphoid Organ-Residing ILC3s Reveals a Quiescent State in the Absence of Inflammation. 
           b) Unsuspected human immunodeficiency virus infection presenting as immunoglobulin G4-related lymphadenopathy: a case report. 
           c) Zebra Fish Lacking Adaptive Immunity Acquire an Antiviral Alert State Characterized by Upregulated Gene Expression of Apoptosis, Multigene Families, and Interferon-Related Genes. 
           d) Comparative studies of oxaliplatin-based platinum(iv) complexes in different in vitro and in vivo tumor models. 

3) Procurando no portal por "acquired OR absence OR organs"
    ->  1.272.928 documentos encontrados
    -> títulos dos 4 primeiros da lista:
           a) Infecções comunitárias do trato urinário em Divinópolis, MG: avaliação do perfil de resistência bacteriana e do manejo clínico / Infecciones del tracto urinário adquiridas en la comunidad en Divinópolis, Brasil: evaluación del perfil de la resistencia bacteriana y la gestión clínica / Community-acquired urinary tract infections in Divinópolis, Brazil: assesment of bacterial resistance profile and clinical management 
          b) El valor del Instrumento Diagnóstico de la Complejidad en Cuidados Paliativos para identificar la complejidad en pacientes tributarios de cuidados paliativos / The value of the Diagnostic Tool for Complexity in Palliative Care for the assessment of palliative patients  
          c) Discapacidad laboral auto-percibida en trabajadores de un centro de educación especial / Self-Perceived work disability in a school of children with special needs 
          d) Miopatía de depósito de nemalina y artrogriposis congénita / Nemaline myopathy and congenital arthrogryposis 

4) Procurando no serviço de documentos similares por "acquired absence of organs, not elsewhere classified"
      -> pelo menos os 6 primeiros tem todos ou quase todos os ngramas presentes no texto de pesquisa
      -> títulos dos 4 primeiros da lista:
           a) Malignancies in the acquired immunodeficiency syndrome.
           b) Chimaeric mice with disruption of the gene coding for phosphatidylinositol glycan class A (Pig-a) were defective in embryogenesis and spermatogenesis.
           c) Intravital imaging of the mouse thymus using 2-photon Microscopy.
           d) Pathogenesis, clinical features, and treatment advances in mastocytosis.

**Comment by renatomurasaki** [comment]
@heitorbarbieri dos cenários descritos, o melhor é o 2. O InfoButton precisa ser preciso.
Um algoritmo baseado na construção de estratégias de busca seria:
1. Busca o conceito (uma ou mais palavras) no índice permutado do DeCS
2. Encontrando, utilizar mh:, como também combinar com ti: por conta dos documentos ainda não indexados (mais recentes)
3. Não existinho, buscar no ti: e tentar garimpar os descritores utilizados na indexação destes documentos recuperados pelo título
4. Sair com uma estratégia de busca no seguinte estilo: (mh: ...) or (ti: ...)

**Comment by heitorbarbieri** [comment]
@renatomurasaki  realizaremos uma reunião comigo, Arthur e @falbrito para discutirmos sobre a estrutura da base de dados Isis de conversão entre thesauri através do UMLS.

**Comment by heitorbarbieri** [comment]
Sobre a estratégia de busca, a tarefa segue no issue #21

**Comment by heitorbarbieri** [comment]
Da reunião acima citada, obteve-se a indicação de como utilizar uma base de conversão. Veja issue #24
